### Numpy - Python library 
ndarray is 50x faster than list fro algebric operations. 

In [ ]:
import numpy as np
lst1 = [1,2,3,4]

# create numpy array, it is homogeneous
np_arr = np.array(lst1)
print(np_arr, type(np_arr))
print(lst1, type(lst1))

[1 2 3 4] <class 'numpy.ndarray'>
[1, 2, 3, 4] <class 'list'>


In [ ]:
print(f'size : {np_arr.size}, Datatype : {np_arr.dtype}')
print(f'Shape : {np_arr.shape}, Dimention : {np_arr.ndim}')

size : 4, Datatype : int32
Shape : (4,), Dimention : 1


In [ ]:
# generate sequence of num
seq_arr = np.arange(5)
# create seq of zeros 
z_arr = np.zeros(6)
one_arr = np.ones(7)

print(seq_arr, z_arr, one_arr, sep='\n')

[0 1 2 3 4]
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#append
np_arr = np.append(np_arr, 45)
print(np_arr)

# delete at index 
np_arr1 = np.delete(np_arr, 4)
print(np_arr1)

# sort
np_arr2 = np.sort(np_arr)

# reshaping
np_sh = np.reshape(np_arr1, (2,2))
print(np_sh)

[ 1  2  3  4 45]
[1 2 3 4]
[[1 2]
 [3 4]]


In [ ]:
# slicing
#  np_arr[start,end, jump]
print(np_arr[1:-1:2])
# can use , in case of more than 1d array 
# eg np_arr[::1, 3:4:2]

[2 4]
